<template>
  <div class="gameView">
    <div style="margin-bottom: 20px">
      <button
        :class="myAnswer == 'yes' ? ['selected', 'yes'] : ['yes']"
        :disabled="gameState != 'answer' || waiting > 0"
        @click="answer('yes')"
      >
        Yes
      </button>
      <button
        :class="myAnswer == 'no' ? ['selected', 'no'] : ['no']"
        :disabled="gameState != 'answer' || waiting > 0"
        @click="answer('no')"
      >
        No
      </button>
    </div>
    <div v-if="currentQuestionId != null">
      {{ questionTitle }}
    </div>
    <div v-if="waiting > 0" class="loadingio-spinner-rolling-0efhjb6yyalu">
      <div class="ldio-1mmitfc0jou">
        <div></div>
      </div>
    </div>
  </div>
</template>

<script>
import { useCookies } from "vue3-cookies";

export default {
  name: "GameView",
  components: {},
  setup() {
    const { cookies } = useCookies();
    return { cookies };
  },
  props: {
    gameId: String,
  },
  inject: ["api_url"],
  data() {
    return {
      gameState: null,
      myAnswer: null,
      currentQuestionId: null,
      questionTitle: null,
      waiting: 0,
      fetchTimer: null,
    };
  },
  mounted() {
    this.fetchTimer = setInterval(() => this.fetchGameState(), 2000);
    this.fetchGameState();
  },
  unmounted() {
    clearInterval(this.fetchTimer);
  },
  watch: {
    currentQuestionId: function () {
      this.fetchQuestionInfo();
    },
  },
  methods: {
    fetchGameState() {
      fetch(this.api_url + "/game/" + this.gameId)
        .then((res) => {
          return res.json();
        })
        .then((data) => {
          this.gameState = data.state;
          this.currentQuestionId = data.current_question;
        })
        .catch((err) => {
          console.log("Failed retrieving game state...", err);
        });
    },
    fetchQuestionInfo() {
      fetch(
        this.api_url +
          "/game/" +
          this.gameId +
          "/question/" +
          this.currentQuestionId
      )
        .then((res) => res.json())
        .then((data) => {
          let playerId = this.cookies.get("playerId");
          this.myAnswer = data.answers[playerId];
          this.questionTitle = data.title;
        })
        .catch((err) => {
          console.log("Failed retrieving question info...", err);
        });
    },
    answer(value) {
      this.waiting++;
      this.waitingAnswerSubmit++;
      fetch(
        this.api_url +
          "/game/" +
          this.gameId +
          "/question/" +
          this.currentQuestionId,
        {
          method: "post",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            answer: value,
            cookie: this.cookies.get("playerCookie"),
          }),
        }
      )
        .then(async (res) => {
          if (!res.ok) {
            const error = await res.json();
            throw Error(error.error);
          }
          return res.json();
        })
        .then(() => {
          this.myAnswer = value;
          this.waiting--;
        })
        .catch((err) => {
          this.waiting--;
          this.error =
            "Something was wrong with the parameters perhaps.. " + err.message;
        });
    },
  },
};
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
.gameView {
  font-size: 2em;
}

button {
  font-size: 1em;
  width: 90%;
  height: 100px;
  border-radius: 0.4em;
  color: black;
}

button:disabled {
  color: gray;
}

/* #89b3eb; */
button.yes.selected {
  background-color: #a1d392;
}
button.no.selected {
  background-color: #ec9a9a;
}

/* Spinning wheel */
@keyframes ldio-1mmitfc0jou {
  0% {
    transform: translate(-50%, -50%) rotate(0deg);
  }
  100% {
    transform: translate(-50%, -50%) rotate(360deg);
  }
}
.ldio-1mmitfc0jou div {
  position: absolute;
  width: 62px;
  height: 62px;
  border: 8px solid #e15b64;
  border-top-color: transparent;
  border-radius: 50%;
}
.ldio-1mmitfc0jou div {
  animation: ldio-1mmitfc0jou 1s linear infinite;
  top: 50px;
  left: 50px;
}
.loadingio-spinner-rolling-0efhjb6yyalu {
  width: 58px;
  height: 58px;
  display: inline-block;
  overflow: hidden;
  background: #ffffff;
}
.ldio-1mmitfc0jou {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(0.58);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-1mmitfc0jou div {
  box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>
